crawler:
  Config:
    MAX_WORKERS: 5
    REQUEST_TIMEOUT: 60
    LOG_LEVEL: 0


# Level Numeric value 
# CRITICAL  50
# ERROR     40
# WARNING   30
# INFO      20
# DEBUG     10
# NOTSET    0

  urls:
    - https://www.foxnews.com/
  
  dict:
    - filepath